server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:market}
        username: ${POSTGRES_USER:market}
        password: ${POSTGRES_PASSWORD:market}
        driver-class-name: org.postgresql.Driver

    flyway:
        schemas: public
        validate-migration-naming: true

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                default_schema: public
                format_sql: true
                jdbc.lob.non_contextual_creation: true
    sql:
        init:
            mode: never
