server:
    port: 8080

spring:
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
management:
    endpoints:
        web:
            exposure:
                include: mappings

jwt:
    secret: ${JWT_SECRET:h3Kjud9HuTrFpPrHj3xxlP8joS/HDnKFy59bW8XAMs4=}
    expiration: ${JWT_EXPIRATION:3600000}
