spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: mp_user
    password: mp_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  sql:
    init:
      mode: never

server:
  port: 8080